### PR TITLE
Marker reset

### PR DESCRIPTION
**Pull request by b-n**

### CODE REVIEW

**Comment by b-n** [comment]
Sorry, wasn't meant to send the PR

**Comment by jojorb** [comment]
hey @nzchicken were you on the PP slack ? hey btw nice yarn and code!

**Comment by b-n** [comment]
Hey @RobyRemzy, nope, haven't seen/been invited to the slack.

@beerecca and I were looking through the master repo on the weekend, but neglected to look at the forks and issues (sorry, being a useless dev on that one). We ended up pretty much making an end to end of this project, however have picked some other design choices in terms of mapping and database (google sheets with github integration for data exchange). Not sure how that fits in with what you guys were wanting/expecting. Have a look at the "live" version though: http://nzchicken.github.io/precious-plastic-map/build

**Comment by jojorb** [comment]
yes when i read globally your code it look cool and the live is heaven better. Sure you did a work and i like it, we may take a few thing from you guys :+1:  have fun!

**Pull request closed without merging**
